### ISSUE TITLE
Alinear videos en sección de social engineering

### ISSUE THREAD

**Issue by CesarMtzV** [PatoGuereque/Proyecto-APIS#16]
En la parte donde se muestran los dos videos sobre social engineering, no se encuentran alineados.
Tambien hay que agregar un poco de margen entre los videos y el botón para regresar al inicio.

**Comment by PatoGuereque** [comment]
También hacer el tamaño de los videos responsivo

![image](https://user-images.githubusercontent.com/19732552/142962475-bd28b3e9-6769-4a0c-8b69-6aa40ebfea43.png)
